# models  generic tests: unique, not_null, relationships, accepted_values
# see sql in target/compiled/bnbdata/models/schema
# description => docs note
version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table with Airbnb listings
    columns:

      - name: listing_id
        description: PK for the listing
        tests:
          - unique
          - not_null

      - name: host_id
        description: FK to host table
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Type of the apartment / room
        tests:
          - accepted_values:
              values: ['Entire home/apt','Private room','Shared room','Hotel room']

      # custom generic test [macro]
      - name: minimum_nights
        description: '{{ doc("docs_listing_cleansed_min_nights") }}'
        tests:
          - positive_value